{
    'name': 'Theme Common',
    'description': 'Theme Common',
    'category': 'Hidden',
    'version': '1.0',
    'author': 'Odoo SA',
    'depends': ['website_less'],
    'data': [
        # image placeholder
        'data/image_content.xml',
        # from theme clean
        'views/s_big_image.xml',
        'views/s_big_image_parallax.xml',
        'views/s_color_blocks_2.xml',
        'views/s_color_blocks_4.xml',
        'views/s_column.xml',
        'views/s_discount.xml',
        'views/s_event_list.xml',
        'views/s_icon_box.xml',
        'views/s_icon_box_circle.xml',
        'views/s_icon_box_square.xml',
        'views/s_image_text_2.xml',
        'views/s_lead_bar.xml',
        'views/s_logo_bar.xml',
        'views/s_pricing.xml',
        'views/s_process_step.xml',
        'views/s_progress_bar.xml',
        'views/s_profile.xml',
        'views/s_separator_color.xml',
        'views/s_separator_shade.xml',
        'views/s_slide_banner.xml',
        'views/s_team_profiles.xml',
        'views/s_text.xml',
        'views/s_text_image_2.xml',
        'views/s_text_highlight.xml',
        'views/s_three_columns_circle.xml',
        'views/s_timeline.xml',
        'views/s_timeline_compact.xml',
        'views/s_title_small.xml',
        'views/s_two_columns.xml',
    ],
    'demo': [
        'demo/demo.xml',
    ],
    'application': False,
}
